# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 246590c36533d0c8f00fe06592cccac4247444c50b668b4505a891f0aa1b9707368c8da39e7005b094991034c786bb7721c38365caa1066f17e44abd03beb5d6

test:
  secret_key_base: 6aa54f3b4e731321405d231b4def82b8df3fde923d469eaa07e87420beac8b5d13b7a2a5b3c47203739a30f02fb2c2dcff4f16c3e49d0de0641d0524313a55e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
